#compdef ports

# Zsh completion for ports — generated by Aesh.
# Place this file in a directory listed in $fpath (e.g., ~/.zsh/completions/)

_ports() {
    local -a commands
    commands=(
        'ps:Show all running dev processes'
        'watch:Real-time monitoring (poll every 1s)'
        'clean:Find and interactively kill orphaned processes'
        'completions:Generate shell completion scripts'
    )

    _arguments -C \
        '--all[Show all ports including system services]' \
        '(-p)--port[Port number to inspect in detail]:Port number to inspect in detail:' \
        '(--port)-p[Port number to inspect in detail]:Port number to inspect in detail:' \
        '--group[Group ports by process (default\: true, use --no-group to expand)]' \
        '--no-group[Disable group]' \
        '1:command:->cmd' \
        '*::arg:->args'

    case $state in
        cmd)
            _describe 'command' commands
            ;;
        args)
            case ${words[1]} in
                ps)
                    _ports_ps
                    ;;
                watch)
                    _ports_watch
                    ;;
                clean)
                    _ports_clean
                    ;;
                completions)
                    _ports_completions
                    ;;
            esac
            ;;
    esac
}

_ports_ps() {
    _arguments \
        '--all[Show all processes, not just dev processes]' \
}

_ports_watch() {
    _arguments \
        '--all[Show all ports including system services]' \
}

_ports_clean() {
    _arguments \
}

_ports_completions() {
    _arguments \
        '(-s)--shell[Target shell\: BASH, ZSH, FISH, or POWERSHELL]:Target shell\: BASH, ZSH, FISH, or POWERSHELL:(bash zsh fish pwsh )' \
        '(--shell)-s[Target shell\: BASH, ZSH, FISH, or POWERSHELL]:Target shell\: BASH, ZSH, FISH, or POWERSHELL:(bash zsh fish pwsh )' \
        '(-o)--output[Output directory (default\: ./completions)]:Output directory (default\: ./completions):' \
        '(--output)-o[Output directory (default\: ./completions)]:Output directory (default\: ./completions):' \
}

_ports "$@"
