#!/usr/bin/env bash

# Bash completion for ports — generated by Aesh.
# Source this file or place it in /etc/bash_completion.d/

# Fallback if bash-completion is not installed
type _init_completion &>/dev/null || _init_completion() {
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    words=("${COMP_WORDS[@]}")
    cword=$COMP_CWORD
}

# Fallback if _filedir is not available
type _filedir &>/dev/null || _filedir() { COMPREPLY=( $(compgen -f -- "$cur") ); }

_complete_ports() {
    local cur prev words cword
    _init_completion || return

    local subcmd=""
    local i
    for ((i=1; i < cword; i++)); do
        case "${words[i]}" in
            ps) subcmd="ps"; break;;
            watch) subcmd="watch"; break;;
            clean) subcmd="clean"; break;;
            completions) subcmd="completions"; break;;
        esac
    done

    case "$subcmd" in
        ps) _cmd_ports_ps; return;;
        watch) _cmd_ports_watch; return;;
        clean) _cmd_ports_clean; return;;
        completions) _cmd_ports_completions; return;;
    esac

    _cmd_ports
}

_cmd_ports() {
    local no_value_opts=" --all --group --no-group"
    local value_opts=" --port -p"
    local subcmds=" ps watch clean completions"

    case "$prev" in
        --port|-p)
            return;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$no_value_opts $value_opts" -- "$cur") )
    else
        COMPREPLY=( $(compgen -W "$subcmds" -- "$cur") )
    fi
}

_cmd_ports_ps() {
    local no_value_opts=" --all"
    local value_opts=""

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$no_value_opts $value_opts" -- "$cur") )
    else
        COMPREPLY=( $(compgen -W "$no_value_opts $value_opts" -- "$cur") )
    fi
}

_cmd_ports_watch() {
    local no_value_opts=" --all"
    local value_opts=""

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$no_value_opts $value_opts" -- "$cur") )
    else
        COMPREPLY=( $(compgen -W "$no_value_opts $value_opts" -- "$cur") )
    fi
}

_cmd_ports_clean() {
    local no_value_opts=""
    local value_opts=""

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$no_value_opts $value_opts" -- "$cur") )
    else
        COMPREPLY=( $(compgen -W "$no_value_opts $value_opts" -- "$cur") )
    fi
}

_cmd_ports_completions() {
    local no_value_opts=""
    local value_opts=" --shell -s --output -o"

    case "$prev" in
        --shell|-s)
            COMPREPLY=( $(compgen -W "bash zsh fish pwsh" -- "$cur") )
            return;;
        --output|-o)
            return;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$no_value_opts $value_opts" -- "$cur") )
    else
        COMPREPLY=( $(compgen -W "$no_value_opts $value_opts" -- "$cur") )
    fi
}

complete -o default -F _complete_ports ports
